version: "3.7"

networks:
  traefik-public:
    external: true
    
volumes:
  pastemd-backend:

services:
  pastemd-backend:
    image: registry.dev.gbms.site/pastemd-backend
    networks:
      - traefik-public

    volumes:
      - pastemd-backend:/data

    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.pastemd-backend.rule=Host(`api.pastemd.gbms.site`)
        - traefik.http.routers.pastemd-backend-http.entrypoints=http
        - traefik.http.routers.pastemd-backend-http.service=pastemd-backend
        - traefik.http.routers.pastemd-backend-http.rule=Host(`api.pastemd.gbms.site`)
        - traefik.http.routers.pastemd-backend-http.middlewares=https-redirect
        - traefik.http.routers.pastemd-backend.entrypoints=https
        - traefik.http.routers.pastemd-backend.tls=true
        - traefik.http.routers.pastemd-backend.tls.certresolver=le
        - traefik.http.services.pastemd-backend.loadbalancer.server.port=8000
        - traefik.http.routers.pastemd-backend.service=pastemd-backend
